accounts/urls.py
from django.conf.urls import url, include
from django.urls import path
from .views import register, profile, logout, login, reset, sendMail
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    url(r'^register/$', register, name='register'),
    url(r'^profile/$', profile, name='profile'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^login/$', login, name='login'),
    url(r'^reset/$', reset, name='reset'),
    path('', sendMail),


]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

class PasswordResetForm(forms.Form):
    email = forms.CharField()

class EmailForm(forms.Form):
    email = forms.EmailField()
    message = forms.CharField()

class UserLoginForm(forms.Form):
    """
    Used by the user to enter login credentials
    """
    username_or_email = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(UserCreationForm):
    """
    Used by the user to sign up with the website
    """
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Password Confirmation',
        widget=forms.PasswordInput
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if User.objects.filter(email=email).exclude(username=username):
            raise forms.ValidationError(u'Email addresses must be unique.')
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if not password1 or not password2:
            raise ValidationError("Password must not be empty")

        if password1 != password2:
            raise ValidationError("Passwords do not match")

        return password2

accounts/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.contrib import messages, auth
from django.urls import reverse
from .forms import PasswordResetForm, UserLoginForm, UserRegistrationForm
from django.template.context_processors import csrf
from django.contrib.auth.decorators import login_required
from .forms import EmailForm
from django.core.mail import send_mail
from django.conf import settings

# Create your views here.
def logout(request):
    auth.logout(request)
    messages.success(request, 'You have successfully logged out')
    return redirect(reverse('accounts:login'))


def login(request):
    if request.method == 'POST':
        user_form = UserLoginForm(request.POST)
        if user_form.is_valid():
            user = auth.authenticate(username=request.POST['username_or_email'],
                                     password=request.POST['password'])

            if user:
                auth.login(request, user)
                messages.error(request, "You have successfully logged in")

                if request.GET and request.GET['next'] !='':
                    next = request.GET['next']
                    return HttpResponseRedirect(next)
                else:
                    return redirect(reverse('accounts:profile'))
            else:
                user_form.add_error(None, "Your username or password are incorrect")
    else:
        user_form = UserLoginForm()

    args = {'user_form': user_form, 'next': request.GET.get('next', '')}
    return render(request, 'login.html', args)

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            user_form.save()

            user = auth.authenticate(username=request.POST.get('username'),
                                     password=request.POST.get('password1'))

            if user:
                auth.login(request, user)
                messages.success(request, "You have successfully registered")
                
                if request.GET and request.GET['next'] !='':
                    next = request.GET['next']
                    return HttpResponseRedirect(next)
                else:
                    return redirect('accounts:profile')
            else:
                messages.error(request, "unable to log you in at this time!")
    else:
        user_form = UserRegistrationForm()

    args = {'user_form': user_form}
    return render(request, 'register.html', args)
    
@login_required
def profile(request):
    return render(request, 'profile.html')

def reset(request):
    # create a variable to keep track of the form
    messageSent = False

    # check if form has been submitted
    if request.method == 'POST':

        form = EmailForm(request.POST)

        # check if data from the form is clean
        if form.is_valid():
            cd = form.cleaned_data
            subject = "Sending an email with Django"
            message = cd['message']

            # send the email to the recipent
            send_mail(subject, message,
                      settings.DEFAULT_FROM_EMAIL, [cd['email']])

            # set the variable initially created to True
            messageSent = True

    else:
        form = EmailForm()

    return render(request, 'password_reset_form.html', {

        'form': form,
        'messageSent': messageSent,

    })

def sendMail(request):

    # create a variable to keep track of the form
    messageSent = False

    # check if form has been submitted
    if request.method == 'POST':

        form = EmailForm(request.POST)

        # check if data from the form is clean
        if form.is_valid():
            cd = form.cleaned_data
            subject = "Sending an email with Django"
            message = cd['message']

            # send the email to the recipent
            send_mail(subject, message,
                      settings.DEFAULT_FROM_EMAIL, [cd['recipient']])

            # set the variable initially created to True
            messageSent = True

    else:
        form = EmailForm()

    return render(request, 'password_reset_form.html', {

        'form': form,
        'messageSent': messageSent,

    })

accounts/templates/logged_out.html
{% extends "base_generic.html" %}

{% block content %}
  <p>Logged out!</p>
  <a href="{% url 'login'%}">Click here to login again.</a>
{% endblock %}

accounts/templates/login.html
{% extends "shop/base.html" %}
{% load bootstrap_tags %}
{% block content %}


    <form method="post" action="{% url 'accounts:login' %}?next={{ next }}" class="accountform">
        <fieldset class="form-group">
            <legend>Login</legend>
            
            {% if next %}
                <p>No account? <a href="{% url 'accounts:register' %}?next={{ next }}">Sign up</a> now.</p>
            {% else %}        
                <p>No account? <a href="{% url 'accounts:register' %}">Sign up</a> now.</p>
            {% endif %}
            
            <br>
            {% csrf_token %}
            {{ user_form | as_bootstrap }}
            
             <p><a href="{% url 'accounts:reset' %}">Forgot my password</a></p>
             
            <button type="submit" class="btn btn-primary">Login</button>
        </fieldset>
    </form>
{% endblock %}
{% block footer %}
{% endblock %}

accounts/templates/logout.html
{% extends "shop/base.html" %}

{% block content %}
  <p>Logged out!</p>
  <a href="{% url 'accounts:login'%}">Click here to login again.</a>
{% endblock %}

accounts/templates/password_reset_complete.html
{% extends "shop/base.html" %}
{% block content %}
  <h1>The password has been changed!</h1>
  <p><a href="{% url 'accounts:login' %}">log in again?</a></p>
{% endblock %}

accounts/templates/password_reset_confirm.html
{% extends "shop/base.html" %}

{% block content %}
    {% if validlink %}
        <p>Please enter (and confirm) your new password.</p>
        <form action="" method="post">
        {% csrf_token %}
            <table>
                <tr>
                    <td>{{ form.new_password1.errors }}
                        <label for="id_new_password1">New password:</label></td>
                    <td>{{ form.new_password1 }}</td>
                </tr>
                <tr>
                    <td>{{ form.new_password2.errors }}
                        <label for="id_new_password2">Confirm password:</label></td>
                    <td>{{ form.new_password2 }}</td>
                </tr>
                <tr>
                    <td></td>
                    <td><input type="submit" value="Change my password" /></td>
                </tr>
            </table>
        </form>
    {% else %}
        <h1>Password reset failed</h1>
        <p>The password reset link was invalid, possibly because it has already been used. Please request a new password reset.</p>
    {% endif %}
{% endblock %}

accounts/templates/password_reset_done.html
{% extends "shop/base.html" %}

{% block content %}
  <p>We've emailed you instructions for setting your password. If they haven't arrived in a few minutes, check your spam folder.</p>
{% endblock %}

accounts/templates/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

accounts/templates/password_reset_form.html
{% extends "shop/base.html" %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <title>Send Email</title>
  </head>
  <body>
    {% if messageSent %}
    <div class="container">
      <h3><strong>Email successfully sent</strong></h3>
      <p>Your password reset has been successfully sent to the email provided. Thank you!</p>
    </div>
    {% else %}
    <div class="container">
      <h3><strong>Send E-mail</strong></h3>

      <form method="post">
        {% csrf_token %} {{ form.as_p }}
        <br />
        <div class="text-center">
          <input
            type="submit"
            class="btn btn-secondary"
            style="width: 100%"
            value="Send e-mail"
          />
        </div>
      </form>
    </div>
    {% endif %}
  </body>
</html>
{% endblock %}
{% block footer %}
{% endblock %}

accounts/templates/profile.html
{% extends "shop/base.html" %}
{% load static %}
{% block content %}
    <h2>Success!</h2>
    <p>You are logged in as {{ user.email }} </p>

    <a href="shop:base" style="color:white;">Return to Home Page</a>
{% endblock %}
{% block footer %}
{% endblock %}

accounts/templates/register.html
{% extends "shop/base.html" %}
{% load bootstrap_tags %}
{% block content %}
    <form method="post" action="{% url 'accounts:register' %}" class="accountform">
        <fieldset class="form-group">
            <legend>Create a new account</legend>
            <p>Already got an account? <a href="{% url 'accounts:login' %}">Sign In</a></p>
            {% csrf_token %}
            {{  user_form | as_bootstrap }}
            <button type="submit" class="btn btn-primary">Create account</button>
        </fieldset>
    </form>
{% endblock %}
{% block footer %}
{% endblock %}